### ISSUE TITLE
Improve OC-tool handling of git sync issues

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#10]
During regular OC-tool usage done in between multiple days/weeks, the script might create or update sync'ed files on standard local folders as found on the rusty-bits git repository. Fast forward to another run of OC-tool days after, the script may fail with no warning whatsoever about what went wrong, which can be misleading if the user is not familiar with the tool. Unless the user knows to look at tool.log log file for clues, there are zero suggestions from the script about why the tool just failed. Perhaps a simple message as "Review tool.log logfile for errors", after the "For help use %1 -h" message should suffice, if automation of such error recoveries cannot be implemented.

See tool output example below.

hquest@hquest OC-tool % ./OC-tool -s INPUT/config.debug.plist
For help use './OC-tool -h'

Using INPUT/config.debug.plist

Checking for updates ... 
OC-tool - **%**                                                                     
hquest@hquest OC-tool % more tool.log 
error: Your local changes to the following files would be overwritten by merge:
        Docs/Sample.plist
Please commit your changes or stash them before you merge.
Aborting
hquest@hquest OC-tool %

**Comment by rusty-bits** [comment]
That _should_ have been fixed 5 days ago with commit 2912a51, but I did break a few other things that day, so ...  
Also, if your version of OC-tool is older than 5 days, it wouldn't get the update because of the git merge warning.  I'm assuming you were able to get it working since you knew enough to look in the log, please let me know if there is an issue.  

![Screen Shot 2020-01-20 at 3 20 13 PM](https://user-images.githubusercontent.com/46965981/72756205-888a7880-3b9a-11ea-9f61-a2e01aac4917.png)

**Comment by HQuest** [comment]
On a first glance, the code seems to correct what I reported, so I take it should be working already after I re-ran it earlier today during the report. 

Hope you don't mind me opening issues; I'm good at breaking stuff 👍
