### ISSUE TITLE
Freeze when building new config/efi from TUI

### ISSUE THREAD

**Issue by namnnumbr** [rusty-bits/OC-tool#11]
If I go into the TUI, edit with the editor (e option), make changes, and try to directly build new efi (g-option), the program stalls at this line:

```Writing new config.plist to /Users/USER/Desktop/Hackintosh/OC-tool/Docs/config.plist ... ```
And the config file that it generates is corrupt.

**Comment by rusty-bits** [comment]
Can you show me what you get in the tool.log file when you get that error, it might help me track down the problem.  

And also if you could include the full command you are running and a picture of the summary screen before you enter the e option that could help as well.  

The only time I've seen that type of error is when there is an issue with the initial config.plist, but I may have broken something else with my latest update.

**Comment by namnnumbr** [comment]
log shows:

```
/usr/bin/plutil
/Users/USER/Desktop/Hackintosh/OC-tool/INPUT/temp/config.plist: OK
```

I'm attaching (or, attempting to) several images that show the basic summary, the page I was on, and the stalled plist creation.  

During testing -- this only happens if I edit the config.  If I don't edit and hit 'g', everything works fine.  I played around with editing both my kext list and my boot args.  config.plist creation stalled both times.
<img width="920" alt="Screen Shot 2020-01-30 at 5 15 46 PM" src="https://user-images.githubusercontent.com/29991822/73495578-bea3d580-43ae-11ea-88de-1e5f128daab4.png">
<img width="920" alt="Screen Shot 2020-01-30 at 5 16 29 PM" src="https://user-images.githubusercontent.com/29991822/73495579-bea3d580-43ae-11ea-9f53-e4855238c250.png">
<img width="992" alt="Screen Shot 2020-01-30 at 5 18 11 PM" src="https://user-images.githubusercontent.com/29991822/73495580-bea3d580-43ae-11ea-8a55-f3733640cb08.png">

**Comment by rusty-bits** [comment]
Thanks for the quick reply.

Okay, a few things look odd  
![Screen Shot 2020-01-30 at 5 44 37 PM](https://user-images.githubusercontent.com/46965981/73497333-8c7f7d00-4388-11ea-875b-c3c30c56854a.png)
![Screen Shot 2020-01-30 at 5 44 44 PM](https://user-images.githubusercontent.com/46965981/73497339-8ee1d700-4388-11ea-9fce-dd5e52bf916c.png)
  
The kext name being blue is odd, OC-tool might be inserting some characters in while editing  
and the missing line on the edit screen is odd, OC-tool might have a blank

and then there is this  
![Screen Shot 2020-01-30 at 5 51 39 PM](https://user-images.githubusercontent.com/46965981/73497645-48d94300-4389-11ea-84d5-e7f7ef273374.png)

a blank at the end of Kernel > Add  
it could be a problem with how I number resources internally  

are you able to share your config.plist (without the MLB, SystemSerialNumber and SystemUUID)  
also, what happens if you edit the Sample.plist?  
./OC-tool -t ./Docs/Sample.plist

**Comment by namnnumbr** [comment]
Could build ok from sample using TUI, thought I didn't go as far as to replicate my current config.

plist attached.
[configcopy.plist.zip](https://github.com/rusty-bits/OC-tool/files/4136904/configcopy.plist.zip)

Also -- you've pointed out the text in blue - interesting to note it's not blue if I build without the TUI...

**Comment by rusty-bits** [comment]
Don't worry about how you sound, doesn't bother me at all  

I found a few things in your config.plist causing issues with OC-tool    

![Screen Shot 2020-01-30 at 9 27 31 PM](https://user-images.githubusercontent.com/46965981/73507858-489c7000-43a8-11ea-8d86-6de75c5013e3.png)
<dict/> is valid xml, but OC-tool doesn't know what to do with it yet, you'll either need to remove the PciRoot(0x0)/Pci(0x1b,0x0) entirely, or add the layout-id back in  

![Screen Shot 2020-01-30 at 9 29 28 PM](https://user-images.githubusercontent.com/46965981/73508201-4dadef00-43a9-11ea-909e-e5fd15d394a3.png)
Also valid xml, but the ^H character caused display glitches  

![Screen Shot 2020-01-30 at 9 28 36 PM](https://user-images.githubusercontent.com/46965981/73508212-51da0c80-43a9-11ea-88a1-3d25cdc7d354.png)
and this is valid xml as well, but there are no real values in the OpenCore config.plist  

![Screen Shot 2020-01-30 at 9 42 59 PM](https://user-images.githubusercontent.com/46965981/73508301-81891480-43a9-11ea-9f9e-d9385330cbca.png)
You can see in the Configuration.pdf that this should be an integer  

[configcopy.plist.zip](https://github.com/rusty-bits/OC-tool/files/4137348/configcopy.plist.zip)

I made some corrections in your config.plist and it's working okay on this end, but I'd say it still needs some work from you. For example you have USBInjectAll.kext enabled and also had the XhciPortLimit Quirk enabled (I disabled it)  
Let me know if it works for you, and one last question, what have you been using to edit your config.plist?  The order of it is a very scrambled version of the Sample.plist, I'm wondering if the editor you have been using messed with the formatting.

**Comment by namnnumbr** [comment]
Cool, thank you.  Works for me!

I used both xcode and your OC-tool to work on this config, but I was copy/pasting from an opencore EFI (OC v0.5.2 maybe?) that I had working for a different motherboard.  So its possible there was some corruption/strangeness in all of that, or maybe I did something by accident.

At this point I may try completely recreating the config from the sample using OC-tool and see if I can get it clean & working.

**Comment by rusty-bits** [comment]
Glad it worked for you.  

At this point, I strongly recommend using [ProperTree](https://github.com/corpnewt/ProperTree) to edit plist files.  Since OC-tool can't add new kexts and drivers to the config.plist yet.  ProperTree is much lighter than Xcode for just editing a plist.  

Then you can still use OC-tool to edit certain settings, enable/disable quirks etc. 

I just pushed an update to OC-tool and it will now flag the <real> value and change it to <integer> automatically, as well as a few other checks.  

![Screen Shot 2020-02-01 at 8 45 01 AM](https://user-images.githubusercontent.com/46965981/73593195-2a7d5f80-44cf-11ea-96d5-674e0644e662.png)
I noticed one last thing in your plist causing OC-tool to choke, going to put a check in for that too
