### ISSUE TITLE
VirtualSMC-1.1.1-DEBUG/Drivers/VirtualSmc.efi: No such file or directory

### ISSUE THREAD

**Issue by whatsnewsisyphus** [rusty-bits/OC-tool#15]
Running a fresh git clone I'm getting VirtualSMC-1.1.1-DEBUG/Drivers/VirtualSmc.efi: No such file or directory, which makes sense since the efi doesnt come with the release that way.

**Comment by rusty-bits** [comment]
Well, that's a big problem on my end. VirtualSmc.efi has been removed from OpenCore 056, but still exists for 055 which I didn't account for at all.  
Right now OC-tool only looks at the latest prebuilts for resources, I'll have to make it look at the prebuilt release instead of prebuilt dailies for certain cases, might take a day or so.  
BTW, If you are running v 0.5.6 of OpenCore you should remove VirtualSmc.efi from your config.plist

**Comment by rusty-bits** [comment]
pointed VirtualSmc.efi back to VirtualSMC-1.0.8
build and copy now succeeds
