### ISSUE TITLE
<data> linebreak additions

### ISSUE THREAD

**Issue by whatsnewsisyphus** [rusty-bits/OC-tool#16]
Not sure if it is intentional or of consequence but the tool adds linebreaks to <data> fields.
![Screenshot 2020-02-12 14 33 20](https://user-images.githubusercontent.com/454772/74370183-abc4d400-4da4-11ea-9235-126571eee6d2.png)

**Comment by rusty-bits** [comment]
It's intentional but not done by OC-tool.  If you run OC-tool on macOS it will use plutil (Apples command line plist utility program) as one of the final steps to make sure the config.plist syntax and format has no errors.
It changes the format of data fields to multi line by default, I'm not even sure there is a way to make it do otherwise,  so I left the format the way plutil makes it.
