### ISSUE TITLE
prev-lang:kbd doesn't accept 'en-US:0'

### ISSUE THREAD

**Issue by snoby** [rusty-bits/OC-tool#20]
Great PROJECT!!!!!
I have a config.plist which has 
```
prev-lang:kbd ( type string) : en-US:0
```
which according to this [doc is valid](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/intel-config.plist/skylake).

>Hint: prev-lang:kbd can be changed into a String so you can input en-US:0 directly instead of converting to HEX

The sample.plist.txt file has it listed as:
```
NVRAM|Add|7C436110-AB2A-4BBB-A880-FE41995C9F82|||data|prev-lang:kbd| "cnUtUlU6MjUy"
```

It's throwing this error

```
Processing config.plist ... done
Checking for missing fields ...
NOTE:	found fields missing from config.plist

	NVRAM > Add > prev-lang:kbd

	You can edit your config.plist manually, or
	use the -t option to select fields to add
	e.g. './OC-tool -t'

Checking for extra fields ...
NOTE:	found extra fields in config.plist

	NVRAM > Add > prev-lang:kbd

	You can edit your config.plist manually, or
	use the -t option to select fields to remove
	e.g. './OC-tool -t'


ERROR: /Users/foo/Dropbox/home_work/osx-amd/round2/OC-tool/INPUT/config.plist does not appear to be an OpenCore plist
	If you don't have an OpenCore plist you can start with the sample provided
	by the acidanthera team.  You can copy the sample to your INPUT directory
	by using this command, but be aware if a config.plist already exists in
	the INPUT directory it will be replaced.

	cp ./Docs/Sample.plist ./INPUT/config.plist

```

I worked around the issue by setting the field to data and putting the HEX value in... I don't know, maybe put some sort of pre - linter in there that says if this field is set to string don't accept?

**Comment by rusty-bits** [comment]
string is probably valid, but I have OC-tool take it's cues from the Sample.plist, that way it doesn't need to know too much about the contents, it uses the Sample.plist as a template on each run

the error your getting isn't for the kbd string, it's because there are sections "missing" from your config.plist
and I put "missing" in quotes because OpenCore will be fine without them, but OC-tool won't because of some choices I made when I started writing it

Right now, OC-tool will die somewhat ungracefully if ACPI > Add, Kernel > Add, UEFI > Drivers, or Misc > Tools are empty in the config.plist
It used to say WARNING: missing <whatever section> but I have that commented out in the code for some reason (okay brain, try to remember why you did this...)
![Screen Shot 2020-03-05 at 9 32 45 AM](https://user-images.githubusercontent.com/46965981/75991299-473cf680-5ec4-11ea-9e91-21d03832b58e.png)

anyways, I threw the first defaults (Enabled:false) from the Sample.plist into your config,
[config.plist.txt](https://github.com/rusty-bits/OC-tool/files/4293474/config.plist.txt)

this is what you should see when it's run
![Screen Shot 2020-03-05 at 9 37 34 AM](https://user-images.githubusercontent.com/46965981/75991811-042f5300-5ec5-11ea-873f-5d4197cb175d.png)

and if you use the -t option it will change the kbd to data type to match the Sample.plist and drop you into the editor so you can change to en-US:0
![Screen Shot 2020-03-05 at 9 43 56 AM](https://user-images.githubusercontent.com/46965981/75992529-19f14800-5ec6-11ea-9fd9-c9f4d33baba0.png)
![Screen Shot 2020-03-05 at 9 44 15 AM](https://user-images.githubusercontent.com/46965981/75992545-1f4e9280-5ec6-11ea-93aa-22d264ed6320.png)

there is a fix in the works for this "missing" issue, but I'll talk about that over in issue #21 you opened because it's more relevant to that problem

**Comment by rusty-bits** [comment]
Found a bug in parsePlistMod.sh that didn't clear a variable when an empty dict was found
Added a line to parsePlistEdit.sh to make OC-tool happy with empty dicts
Added option to OC-tool to ignore plist files with missing sections, closing this ticket
leaving #21 open until I hear from you and others that all is well
