### ISSUE TITLE
[Feature request] Download Beta

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#26]
Hi,
Great software. is there an option to download the OpenCore-0.5.8-RELEASE instead of 0.5.7. with OCBuilder it can download 0.5.8.

Thanks

**Comment by rusty-bits** [comment]
If I understand correctly, you are looking for the release build of the 0.5.8 version?  
If so, yes, OC-tool has always done this.  It's kind of what it was made for since OpenCore changes daily.  You just run OC-tool and it updates any changes without having to update everything.  

If you run ...
`./OC-tool -V`  
it will tell you what versions it will output.  
![3F4E89F5-1292-49E7-88F5-1398F4E7051C](https://user-images.githubusercontent.com/46965981/79982503-6e4f8780-8474-11ea-847a-c68325242c1b.jpeg)

so, currently running  
`./OC-tool` with no options will build release 0.5.7, release version  
`./OC-tool -D` will build release 0.5.7, debug version  
`./OC-tool -s` will build 0.5.8 release version from latest source  
`./OC-tool -sD` will build 0.5.8 debug version from latest source  
`./OC-tool -d` will build 0.5.8 release version from daily precompiled  
`./OC-tool -dD` will build 0.5.8 debug version from daily precompiled  

Is this what you meant?

**Comment by Blurayx** [comment]
Hi,
Thanks for the reply. when I run ./OC-tool -V, I get  "permission denied: ./OC-tool" even when I run it as admin.

**Comment by rusty-bits** [comment]
OC-tool doesn't need any admin permissions.  Make sure you are in the OC-tool directory when you try to run any command, including `./OC-tool -V`  

As to USBInjectAll.kext and IntelMausiEthernet.kext, they don't have a prebuilt release repo to pull anything from.  
You need to either build from source using `./OC-tool -s`  ,  
pull from the OC-tool daily prebuilt repo using `./OC-tool -d`  ,  
or place them in the `extras` folder if you want to use them.  

But, I would use IntelMausi.kext with OpenCore instead of IntelMausiEthernet.kext  
[IntelMausi.kext](https://github.com/acidanthera/IntelMausi) is acidanthera's fork of Mieze's IntelMausiEthernet, and it also has a prebuilt release

**Comment by Blurayx** [comment]
Sorry to be a pain, when you say"Make sure you are in the OC-tool directory when you try to run any command, including ./OC-tool -V"  this is where I get a bit lost 🙂

**Comment by Blurayx** [comment]
What do these errors mean?
<a href="https://imgur.com/KPJeerj"><img src="https://i.imgur.com/KPJeerj.jpg" title="source: imgur.com" /></a>
Thanks

**Comment by rusty-bits** [comment]
It looks like you edited your config.plist and removed entries from a section.  

The Configuration.pdf from acidanthera recommends that all sections be filled in.  
![1D628620-881A-4997-89A2-F9C4891A648B](https://user-images.githubusercontent.com/46965981/80044811-a639e780-84d3-11ea-93dc-d7ca34eff9e0.jpeg)

**Comment by Blurayx** [comment]
compared  to the previous 0.5.8, The latest version some lines have been removed  
previous 0.5.8
<a href="https://imgur.com/zJwhH94"><img src="https://i.imgur.com/zJwhH94.jpg" title="source: imgur.com" /></a>

Current 0.5.8
<a href="https://imgur.com/8Dhv8f6"><img src="https://i.imgur.com/8Dhv8f6.jpg" title="source: imgur.com" /></a>

**Comment by rusty-bits** [comment]
Thanks for pointing that out, I hadn't noticed those were removed.  

I updated OC-tool so it now considers an empty <dict> to be a minor error on commit 28a6e44  
It now only prints a warning if it had to fix some formatting in the plist.

**Comment by Blurayx** [comment]
Excellent, Thanks you 😀

**Comment by Blurayx** [comment]
Update:
Worked perfectly, no errors 😀
<a href="https://imgur.com/vPo7yNf"><img src="https://i.imgur.com/vPo7yNf.jpg" title="source: imgur.com" /></a>
