### ISSUE TITLE
[ 2 Questions]0.5.8 folder Structure & ApfsDriverLoader

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#31]
Hi,
1) A few days ago  Bootstrap was added to the EFI folder structure. Does OC-tool need to be updated or will it always have to be manually added like the Resources folder?
<a href="https://imgur.com/fwxhxA5"><img src="https://i.imgur.com/fwxhxA5.jpg" title="source: imgur.com" /></a>
2)I was surprised I had to add ApfsDriverLoader.efi to the extras folder is this normal?

Thanks

**Comment by rusty-bits** [comment]
OpenCore 0.5.8 includes ApfsDriverLoader internally  
**don't** add it to your extras folder - **remove it** from your config.plist  

I may need to add the Bootstrap folder to OC-tool, otherwise I don't think it will do the Vault signing correctly  
Going to look at that now, thanks

**Comment by rusty-bits** [comment]
Still checking on the Bootstrap folder, might take me a bit, but one other thing that may help you ...  

You don't have to manually add the Resources folder, haven't had to since March 8th, just place the Resources folder with the resources you want to use inside the INPUT folder  
![8B8E48AF-51D9-4FE2-BAB7-3E732DEC5021](https://user-images.githubusercontent.com/46965981/80369166-cf53d280-885b-11ea-8423-e6beffb6a83c.jpeg)

**Comment by Blurayx** [comment]
I didn't realise OpenCore 0.5.8 included ApfsDriverLoader internally. also, I've added my resources folder to the INPUT/Resources folder.
You have been so helpful. Thanks 😀

**Comment by rusty-bits** [comment]
You're helpful as well, and others like you, for pointing out issues  

I think I've made a decision on the Bootstrap folder ...  
If `Misc > Security > BootProtect` is set to `Bootstrap` instead of `None` then OC-tool will create the `\EFI\OC\Bootstrap\` folder and copy BOOTx64.efi into it renamed as `Bootstrap.efi`  

this should eliminate the need to create and copy the Bootstrap folder yourself, should take about an hour or two to add and test the code, thanks

**Comment by Blurayx** [comment]
I've been meaning to ask you, when OC-tool gets updated, Do I need to re-download OC-tool?

**Comment by rusty-bits** [comment]
no need to re-download OC-tool, it checks and updates itself when run  

just pushed an update on commit 21fda1e that will create the Bootstrap folder if needed  

when you run OC-tool it will automatically grab the update and tell you to run it again to continue
