### ISSUE TITLE
Clear Docs/ files prior to try update OC-tool

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#39]
At pretty much every new update of OC-tool, the tool complains about being unable to retrieve files from GitHub. In all instances, it was found there are two docs (Docs/Configuration.pdf and Docs/Differences.pdf) that do not match the upstream files.

Any chance these files can be removed before the tool tries to update itself? Perhaps checking on the tool.log output and taking action if the initial tool update fails, followed by a self-retry, would save bandwidth while improving the tool experience.

**Comment by rusty-bits** [comment]
I'm trying to reproduce the problem on this end.  

I think the problem is related to OC-tool keeping the Configuration and Differences pdf files up to date, even without an update to OC-tool itself.  

I'm thinking that when it sees a new commit for OC-tool it won't pull it if the Configuration.pdf has been updated. Should be a quick fix.

**Comment by rusty-bits** [comment]
should be all set, OC-tool will reset its git and pull the download now when there are changes  

thank you
