### ISSUE TITLE
Resources folder is missing

### ISSUE THREAD

**Issue by abnayak** [rusty-bits/OC-tool#44]
Thanks for the tool, until I came across the tool I was doing manual upgrades which is painful. 

In my config file, I've enabled Boot picker to be External which requires the Resources folder to be present in the EFI folder. I put my Resources folder inside the extras folder but it didn't get copied. Is there any thing am I missing?

Also, if the Boot picker is set to External and Resources folder is not presence, can the script pull the latest Resource folder from opencore project?

**Comment by HQuest** [comment]
Resources folder is to be added under INPUT/ folder, not extras/.

I still don't know why but it is what it is...

**Comment by abnayak** [comment]
> Resources folder is to be added under INPUT/ folder, not extras/.
> 
> I still don't know why but it is what it is...

Adding to INPUT folder works.

**Comment by rusty-bits** [comment]
I'm thinking about having OC-tool check both location to avoid this problem for other users. Any OpenCanopy resource folders that are found in extras will take precedence over any resource folders placed in INPUT.  
I still need to keep resources in the INPUT folder for some things I do on my end, and I also don't want to have OC-tool download and copy every resource just because OpenCanopy is enabled.  The next version will have a picker for resources so the user can select what they want, but that's still a while away.  

Thoughts?

**Comment by HQuest** [comment]
I'm not sure *everything* that is inside extras/ gets copied to the EFI output. I have a lot of kexts and aml files that are not on any of my config files, yet they never find their way into the output folder. Which is what made me wonder why you placed the Resources under INPUT/ instead.

About a pick-and-choose for what to copy, at this point I would keep it simple and copy what the user has there; if anything critical is missing, just print a warning. More likely folks will copy the entire Resources/ folder and let it there as is, so you might be overcomplicating things.

**Comment by rusty-bits** [comment]
It will only copy stuff from extras if they are enabled in the config.plist   
Anything in extras takes priority, for example if you want to try a special build of Lilu.kext you place it in extras and it is used instead of the standard Lilu   
If you want to use your own SSDTs (highly recommend, really the only way to do some things properly) you place them in extras so they are used instead of the generic prebuilts, etc.   

I think I'm going to have it look in both places for the OpenCanopy resources to minimize any confusion.

**Comment by HQuest** [comment]
If a kext or SSDT file is found on the extras/, it is used instead of the one provided by any of the json repositories, so the Resouces/ on extra/ would follow the same standard: if found, copy it; if not, download from OpenCanopy (future) or warn the user (or error if vault sign is set).

This makes sense considering the whole point of OC-tool is to build a set of working EFI files using either the daily prebuilt files or latest and greatest from sources, and the contents of extras/.

I understand the need of using a custom Lilu instead of building one, but if you are today already moving files here and there, I don't see why you couldn't leave them under a a "disabled/" folder laying around with things you don't need active or overridden at certain times.

**Comment by rusty-bits** [comment]
> I don't see why you couldn't leave them under a a "disabled/" folder laying around with things you don't need active or overridden at certain times.  

Since OpenCore is driven by what is enabled or not in the config.plist it makes sense to just copy your files to their proper locations once and let OpenCore do the rest.  Any time you need to make changes you just edit the config.plist and rebuild. You shouldn't need to be "moving files here and there", that's what OC-tool does for you when you make an edit to your config.plist    

Using a `disabled` folder makes me think of Clover where you have to move things into and out of your EFI manually.  I'm trying to avoid that except for the cases when you need to try a specific version of a kext or driver.  That being said, you can always put unneeded items in a `disabled` folder if you want, OC-tool only looks in the root level of the `extras` folder for files.  At times I keep backup and test files in my `extras` folder for easy access.

**Comment by HQuest** [comment]
> except for the cases when you need to try a specific version of a kext or driver
And that's exactly the current problem: We do not have a way, today, to identify if you have to use the kext from extras/ or from source: if the kext is in extras/, then OC-tool will not compile/download the named kext. Unfortunately the Clover way is actually what makes most sense and is currently done for the exceptions above.

You can easily add a check on the TUI to use/ignore locally found kexts, but on CLI, you would need to add a new param for a list of the kexts to either include or exclude, defaulting to the opposite in such events. Other than that, I'll be curious in listening which creative approach is found to get this sorted out :)

**Comment by rusty-bits** [comment]
I'm not sure what the problem is, I might be missing something   

> We do not have a way, today, to identify if you have to use the kext from extras/ or from source   

We do, if the kext, efi, aml etc. is in the root of `extras` OC-tool will use it.   
If OC-tool doesn't find a needed file in `extras` it will download or build it, depending on what option you chose.  
But, maybe I don't know what you mean by "have to use the kext"   

> but on CLI, you would need to add a new param for a list of the kexts to either include or exclude    

there already is a list of what to include or exclude, the `config.plist`   

> You can easily add a check on the TUI to use/ignore locally found kexts   

checking something on the TUI directly edits the config.plist, the modified plist is copied to the `OUTPUT/EFI/OC` folder and is saved in the `INPUT` folder with `modified.` appended to it    

You can continue to use the modified plist if you want with  
  
`./OC-tool -s INPUT/modified.config.plist`   

You can have as many plists as you want for testing, and OC-tool will still build the `OUTPUT/EFI` from them, and will rename your input plist to `config.plist` to keep OpenCore happy.   

`./OC-tool -s INPUT/test1.plist` will build an `EFI` from source using test1.plist for config.plist    
`./OC-tool -d INPUT/mySpecial.plist` will build an `EFI` from the daily prebuilts   
etc.  

OC-tool will always look in the `extras` folder first to find something that is enabled on the `config.plist`, changing something with the TUI doesn't make it `use local/don't use local` it makes it `add this kext to the EFI/don't add this kext to the EFI`   
If the kext is enabled and is inside `extras` then the one from extras will be used   
If the kext is enabled and is not inside `extras` then OC-tool will download or build it   

Like I said, I might be missing the problem. Please let me know.

**Comment by HQuest** [comment]
Say I have a Lilu.kext on extras/. I do call for Lilu.kext on my config.plist.

By default, OC-tool will use the file from extras/, no questions asked. Even while OC-tool knows it can compile one from sources, as Lilu is a supported project for OC-tool to build it. So I have to manually move it out of the way if I want to use the latest from sources.

With that said, there is no way a supported file (Lilu.kext or a SSDT-*.aml) on extras/ to be opted out during build unless you manually move it away from extras/ prior to calling OC-tool.

Which brings us back to the case of Resources under INPUT/ versus extras/. If you use the extras/ for a different purpose than what was documented, then this might be causing this whole discussion. INPUT was created for storing config plist files. Extras was created for other files that may or may not be used in all configurations. Except files that will take precedence are not selectable and you have to move them away in order to not make use of them - aka the Clover disabled method.

Hope this explains; if not, we can learn how to continue use the tool.l, and apologies for causing this whole mess.

In time: beta 4 is out ;)

**Comment by rusty-bits** [comment]
> l, and apologies for causing this whole mess.  

You're not causing any mess at all, I'm glad to hear about issues and suggestions.  

>  INPUT was created for storing config plist files  

Well, it's where OC-tool looks if you don't tell it to use a different file.  The config.plist you want to use can be anywhere and I use the INPUT folder for more than just the default config.plist.  

> Extras was created for other files that may or may not be used in all configurations  

No, extras is for files that OC-tool can't obtain on it's own, or for when you want OC-tool to use a specific version such as when you compile your own SSDTs    

> you have to move them away in order to not make use of them - aka the Clover disabled method  

True, unlikely to change in the near future as it may confuse people as to what they are selecting.  The user can always keep multiple extras folders with files they want.  Just change the name to `extras-disabled` or something like that and only have one folder named `extras` that will be used.  

> we can learn how to continue use the tool   

Well, I know how to use the tool since I wrote it 😉 (just kidding around, I think I know what you meant)

**Comment by HQuest** [comment]
Both the README.md and INPUT/readme.txt tells to place config.plist in this folder (you wrote it 🤣). Anything not part of the standard projects json file is asked to be on extras. I guess I have not expressed myself into the "extras/", but yes, "for files OC-tool can't obtain on it's own or to use specific version" is also to what I mean.

So my understanding was that "INPUT/" is for plists only, anything else on "extras/". Perhaps to settle this once and for all, if a folder tree structure could be added into the tool documentation, with what goes in and where, and how the "priority" system works (local from extras/ first, build or fetch prebuilt second, warning/error if referenced but not found) would clarify anyone's concerns going forward. And me to keep bugging ya!

Cheers.

**Comment by rusty-bits** [comment]
I thought I already had info like that in the wiki, but I don't have a folder tree there, just file and folder descriptions.  Maybe I'll add one.
