### ISSUE TITLE
Why is HfsPlus.efi being copied into extras, even if it is not specified in config.plist?

### ISSUE THREAD

**Issue by chriswayg** [rusty-bits/OC-tool#5]
ver 2.0(191119)

**Comment by rusty-bits** [comment]
short answer - I'm lazy and needed a quick temporary fix  

longer, and a bit snarky, answer - It doesn't, it actually copies HFSPlus.efi into extras, and then makes an Hfs copy. And therein lies my small problem. Acidanthera puts HfsPlus.efi in their Sample.plist, most sources of the efi are HFSPlus.efi. I'm not sure many people have noticed the difference, but I didn't want to code for another edge case in the script. So, for now I just dump them in extras if they're not there already, otherwise the build will fail for many people.  

It is an issue, and hopefully I will come up with a clean solution.

**Comment by rusty-bits** [comment]
added code to use HFSPlus.efi for either HFSPlus.efi or HfsPlus.efi in config.plist  

OC-tool no longer downloads HFSPles.efi when not requested
