### ISSUE TITLE
[Improvement] -q not to silence everything

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#50]
Option -q should not silence OC-tool messages like missing fields on config.plist, modifications/adjustments to the config.plist, or missing files/folders from extra/ or INPUT/ folders. These should always be printed, regardless of -q flag, since they are important remarks that may cause side effects.

The standard redirect "2>&1 > /dev/null" can always be used by the user if he/she doesn't care about any output at all.

**Comment by rusty-bits** [comment]
Good idea, I'll have -q only show warning messages and add on -Q to silence everything (can always check the tool.log for all the messages)

**Comment by HQuest** [comment]
Maybe you could keep -q as is, leave warning messages as no flag, and add a -v (or similar flag) for verbose, displaying what is printed out by default today. This actually seems a more logical approach as many other tools does.

**Comment by rusty-bits** [comment]
I've improved the -q option a bit and realized that the verbose option is not doing what I thought it was.  
To properly fix it the way I want it to work would require something like   
```
exec &> >(tee -a "$LOGFILE)"  
```  
which is invalid in a POSIX shell because of the process redirection, I will keep it in mind and think of ways that I can improve it, ideally I will add a configuration options to the next version (octool) so the user can set there preferred look and feel.   

Also found a bug thanks to you, using -qt or -tq should have been invalid, but wasn't, that's been fixed.  

This fix will have to do for now since I don't want to rewrite OC-tool, but I intend to include your suggestions in octool.  Thanks again.
