### ISSUE TITLE
Certain Acidanthera repo's not build

### ISSUE THREAD

**Issue by locussss** [rusty-bits/OC-tool#7]
Hi!

Is there a specific reason why BrcmPatchRAM isn't build with OC-tool?

**Comment by rusty-bits** [comment]
I left that one out since pieces of it may need to be placed in /System/Library/Extensions or /Library/Extensions which isn't something OC-tool is going to do, but I suppose as long as people know they may need to move kexts around themselves I guess I can include it.  

I've added the acidanthera/BrcmPatchRAM repo to the git_repo.json file. Building from source and downloading from the prebuilts should work for  
BrcmPatchRAM2.kext  
BrcmPatchRAM3.kext  
...   

etc. now
