### ISSUE TITLE
Five return errors

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#70]
Hi
I getitng Five eturn errors but EFI boots without issues. 

<img width="1030" alt="Screenshot 2021-09-07 at 01 56 39" src="https://user-images.githubusercontent.com/2873112/132270056-1cb1b57d-cd72-4c74-9d79-f9b03699d3dd.png">

[tool.log](https://github.com/rusty-bits/OC-tool/files/7118273/tool.log)

Thanks

**Comment by Blurayx** [comment]
My mistake sorry

**Comment by rusty-bits** [comment]
Yeah, I noticed this as well, but I'm not quite sure how to handle this issue.   
OpenCore 0.7.3 has changed the format of the UEFI>Drivers section to be an array of dict values instead of the list of strings it used to be.  
The old method still boots, but ocvalidate sees it as a wrong format and reports it as an error in the config.plist  
I might just leave it as is since it "_works_"  both ways and since I'm also putting more of my effort into the replacement tool, named **octool**

**Comment by Blurayx** [comment]
Looking forward to your new replacement 😀
