### ISSUE TITLE
OpenLinuxBoot.efi - no prebuilt found for OpenLinuxBoot.efi

### ISSUE THREAD

**Issue by miuirussia** [rusty-bits/OC-tool#74]
OpenLinuxBoot.efi is part of OpenCorePkg

```
ERROR:	OpenLinuxBoot.efi - no prebuilt found for OpenLinuxBoot.efi
	OpenLinuxBoot.efi file not found in extras directory
	Check the spelling of the resource, case matters as well.
	Also check the Configuration.pdf and the Sample.plist to be
	sure the resource hasn't been removed or renamed.
	If you are sure you want this resource then you can
	either place OpenLinuxBoot.efi in extras directory to build EFI with OpenLinuxBoot.efi
	or run with -i option to build EFI without OpenLinuxBoot.efi
	for example, try './OC-tool -id'
```

**Comment by rusty-bits** [comment]
thank you, I have added that to the resource list  

Be aware that I probably won't be updating this tool that much since the new version is now working well enough.  You can try [the new octool](https://github.com/rusty-bits/octool) out here.  I have done away with the `extras` directory and just use the `INPUT` dir for all the files you want included.
