### ISSUE TITLE
Output what's updated when using prebuilt binaries

### ISSUE THREAD

**Issue by lignicolos** [rusty-bits/OC-tool#9]
Can the tool be updated to list an output of any new files that it downloads and uses when building OpenCore using the prebuilt binaries? Right now, I run the script and it outputs "Downloading/unzipping needed or updated resources" and then the output as it builds the EFI folder. I'd like to know if any of the components are newer than the previous time the tool was ran successfully. Thanks!

**Comment by rusty-bits** [comment]
OC-tool already tracks clones and updates when building by source, but if I understand correctly you want it to track the versions of prebuilt binaries as well?  

I'm sure I can add that in.  I'll try to get to it later today.

**Comment by lignicolos** [comment]
no rush! I guess the thing I’m never sure about is if I build an EFI folder
today using the prebuilt binaries and then I use the tool again 4 days (or
whatever interval) from now, how can I tell if anything has changed binary
wise between the two builds?

**Comment by rusty-bits** [comment]
Ah, I see what you mean.  OC-tool already does that, there just haven't been any prebuilt releases from acidanthera for the OpenCorePkg since 12-02-2019.  I'm still going to add prebuilt release files to the update.log, I think that's a good idea.  

I'm going to implement a daily prebuilts option soon, but until then if there is an update to the release prebuilts you will see an output like this...  
![A46E20BA-8693-4869-9C0F-24AF75FD0D51](https://user-images.githubusercontent.com/46965981/72096526-5c444180-32e8-11ea-8351-111134178fab.jpeg)

**Comment by rusty-bits** [comment]
OC-tool now also keeps track of downloaded zip files in update.log
